### ISSUE TITLE
Is decision resource-type-short DEC or DECN?

### ISSUE THREAD

**Issue by andrew2net** [metanorma/bipm-editor-guides#4]
In description the resource-type-short for decision is DEC but in examples it is DECN. What is correct?
https://github.com/metanorma/bipm-editor-guides/blob/main/sources/bipm-outcomes-en.adoc#publication-identifier-1

**Comment by ronaldtse** [comment]
From Janet Miles 2022-10-11:

> I’d suggest DECN for Decision, to remove any doubt about DECN/DECL.

So we should use DECN instead. We need to update the document.
