### ISSUE TITLE
Different suffixes for meeting-sequence

### ISSUE THREAD

**Issue by andrew2net** [metanorma/bipm-editor-guides#6]
Shouldn't we use meeting-sequence like `1st`, `2nd`, `3rd`, and `4th` for English language meetings ID? Not sure about French language IDs.
https://github.com/metanorma/bipm-editor-guides/blob/main/sources/bipm-outcomes-en.adoc#publication-identifier

**Comment by opoudjis** [comment]
Already actioned in relaton-bipm. Adding clarification in documentation.
